import { createElement } from "lwc";
import CopilotIntegration from "c/copilotIntegration";

describe("c-copilot-integration", () => {
  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-copilot-integration", {
      is: CopilotIntegration
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
